BestRestaurant/Models/BestRestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurant.Models
{
  public class BestRestaurantContext : DbContext 
  {
    public virtual DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }
    
    public BestRestaurantContext(DbContextOptions options) : base(options) { }
  }
}

BestRestaurant/Models/Cuisine.cs
using MySql.Data.MySqlClient;
using System.Collections.Generic;
using System;

namespace BestRestaurant.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }

    public int CuisineId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; } 
  }  

  public enum CuisineList
  {
    Chinese = 1,
    Japanese = 2,
    Mexican = 3,
    Italian = 4,
    American = 5
  }
}

BestRestaurant/Models/Restaurant.cs
using MySql.Data.MySqlClient;
using System.Collections.Generic;
using System;

namespace BestRestaurant.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public string Location { get; set; }
    public string HoursOfOperation { get; set; }
    public int CuisineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
  }

}

BestRestaurant/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace BestRestaurant.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantContext _db;

    public CuisinesController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.Include(cuisine => cuisine.Restaurants).FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurant/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurant.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    
    public ActionResult Index()
    {
      return View();
    }
  }
}

BestRestaurant/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BestRestaurant.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantContext _db;

    public RestaurantsController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id); 
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id); 
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");

      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurant/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine
<h4>Add a new Cuisine</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <input type="submit" value="Add new cuisine" />
}
<p>@Html.ActionLink("Show all cuisines", "Index")</p>

BestRestaurant/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<h2>Are you sure you want to delete this Cuisine?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to cuisines", "Index")@{
  Layout = "_Layout";
}

BestRestaurant/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
@model BestRestaurant.Models.Cuisine;


<h2>Cuisine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

<ul>
@if (@Model.Restaurants.Count == 0)
{
  <p>no restaurants found</p>
}

@foreach (Restaurant restaurant in @Model.Restaurants)
{
  <li>Name: @restaurant.Name</li>
}
</ul>

<p>@Html.ActionLink("Back to cuisines", "Index")</p>
<p>@Html.ActionLink("Edit cuisine", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete cuisine", "Delete", new { id = Model.CuisineId })</p>

BestRestaurant/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<h2>Edit</h2>

<h4>Edit this Cuisine: @Html.DisplayFor(model => model.Name)</h4>
 
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CuisineId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to cuisines", "Index")</p>

BestRestaurant/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
@model List<BestRestaurant.Models.Cuisine>;

<h1>Cuisines</h1>

@if (@Model.Count == 0)
{
  <h3>No Cuisines have been added yet!</h3>
} 

@foreach (Cuisine cuisine in Model)
{
  <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</li>
}

<p>@Html.ActionLink("Add new cuisine", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurant/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Restaurant List</h1>
<h2>@Html.ActionLink("See all Restaurants", "Index", "Restaurants")</h2>
<h2>@Html.ActionLink("See all Cuisines", "Index", "Cuisines")</h2>

BestRestaurant/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h4>Add a new Restaurant</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    @Html.LabelFor(model => model.Location)
    @Html.TextBoxFor(model => model.Location)
    <br>
    @Html.LabelFor(model => model.HoursOfOperation)
    @Html.TextBoxFor(model => model.HoursOfOperation)


    @Html.LabelFor(model => model.Cuisine)
    @Html.DropDownList("CuisineId")

    <input type="submit" value="Add new Restaurant" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all items", "Index")</p>

BestRestaurant/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

BestRestaurant/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h2>Restaurant Details</h2>
<hr/>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Location): @Html.DisplayFor(model => model.Location)<h3>
<h3>@Html.DisplayNameFor(model => model.HoursOfOperation): @Html.DisplayFor(model => model.HoursOfOperation)<h3>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId })</p>

BestRestaurant/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this restaurant: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RestaurantId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.Location)
    @Html.EditorFor(model => model.Location)

    @Html.LabelFor(model => model.HoursOfOperation)
    @Html.EditorFor(model => model.HoursOfOperation)

    @Html.LabelFor(model => model.Cuisine)
    @Html.DropDownList("CuisineId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
@model List<BestRestaurant.Models.Restaurant>;

<h1>Restuarants</h1>

@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
} 

@foreach (Restaurant restaurant in Model)
{
  <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId }) | @restaurant.Cuisine.Name</li>
}

<p>@Html.ActionLink("Add new Restaurant", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Best Restaurants</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>